Call API
Kirabo19/react-bookstore pull request #6
Opened 2022-12-15 09:42 UTC by Kirabo19

**Refactor the code to use the Bookstore API to add and remove books.**

-  refactor the redux code of the application using middleware to make async requests to the API.
-  Use redux-thunk to fetch data.
-  Add two actions types FETCH_BOOK_SUCCEED and FETCH_BOOK_FAILED.
-  Create 3 functions: getBooks to fetch the book list and display it, addBookReducer to send and add a new book to the API, and removeBookReducer to remove the selected book from the list.

2022-12-15 10:00 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Kirabo19,

Good job so far!
✔️ Books are persisted on the API
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly fix your typos in the documentation. This bookstore yet you have details about math-magicians.

  ![ueis](https://user-images.githubusercontent.com/36542986/207830033-20e8e13a-7d95-4e6c-a004-ee8efee0b8d3.jpg)

- [x] _Check the comments under the review._

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 10:00 UTC, TedLivist commented on src/redux/configureStore.js
> +  // categoriesReducer,
- [x] I don't think there any need to comment out these codes. Kindly uncomment them.

2022-12-15 10:00 UTC, TedLivist commented on src/redux/configureStore.js
> +import thunk from 'redux-thunk';
- [x] You are using the `redux-thunk` for middleware in API calls whereas you are required to use `createAsyncThunk`. Kindly refactor your API calls in the books reducer to use `createAsyncThunk`.

  [Here is the documentation shared with you in the guidelines](https://redux-toolkit.js.org/api/createAsyncThunk)

2022-12-15 10:00 UTC, TedLivist commented on src/components/bookList.js
> -import Form from './form';
- [x] I am unable to add a book because I cannot find the form on the page. Kindly re-add the form and allow for book additions.

  ![image](https://user-images.githubusercontent.com/36542986/207829279-e8976049-53e3-48f8-b27e-07fbb4aeebc6.png)

2022-12-15 10:11 UTC, Kirabo19 commented on src/components/bookList.js
> -import Form from './form';
Hi @ TedLivist, thanks for the heads up

2022-12-20 09:21 UTC, Kirabo19 commented on src/redux/configureStore.js
> +import thunk from 'redux-thunk';
Hi @TedLivist thanks for the information highly appreciate

2022-12-20 09:34 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @Kirabo19,

✔️ Books are well stored and retrieved from the API

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 11:00 UTC, merged